spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567
    #jdbc:mysql://192.168.43.118/sell?characterEncoding=utf-8&useSSL=false
    #jdbc:mysql://192.168.43.246/sell?characterEncoding=utf-8&useSSL=false
    #jdbc:mysql://192.168.0.104/sell?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://192.168.43.118/sell?characterEncoding=utf-8&useSSL=false
    #jdbc:mysql://192.168.0.104/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
